from csv import *
from tkinter import *
from tkinter import messagebox
from datetime import datetime as dt
import pandas as pd
import datetime
import os
date=datetime.date.today()
filename=str(date)+'.csv'
path=os.path.join(os.getcwd(),'data',filename)
try:
        file=open(path)
except FileNotFoundError :
        try:
                open_file=open(path,'w')
                Writer=writer(open_file)
                Writer.writerow(['Date','Time','Kind of Animal','Sex','Age','Color','Breed',"Physically Fit",'Health Acknowledgement','Ongoing Treatment','Veterinarian name','Caretaker/Foster name','caretaker Contact no','caretaker whatsapp','Email','Local Residence','Permanent residence','Adopter\'s name','adoptor Contact no','adoptor whastapp','Line of work','Email','Local Residence','Permanent Residence','incase of moving','pet before or currently','needs to be alone for','when not home','want a gaurd dog'])
                open_file.close()
        except FileNotFoundError:
                os.mkdir(os.path.join(os.getcwd(),'data'))

window=Tk()
window.title('ADOPTION FORM')

def Save():
    row=[date,dt.now().strftime('%I:%M'),entry1.get(),entry2.get(),entry3.get(),entry4.get(),entry5.get(),menu1.get(),entry6.get(),entry7.get(),entry8.get(),entry9.get(),entry10.get(),entry11.get(),entry12.get(),entry13.get(),entry14.get(),entry15.get(),entry16.get(),entry17.get(),entry18.get(),entry19.get(),entry20.get(),entry21.get(),menu2.get(),menu3.get(),menu4.get(),menu5.get(),menu6.get()]
    file=open(path,'a')
    Writer=writer(file)
    Writer.writerow(row)
    file.close()
    entry1.delete(0,END),entry2.delete(0,END),entry3.delete(0,END),entry4.delete(0,END),entry5.delete(0,END),menu1.set('please choose one'),entry6.delete(0,END),entry7.delete(0,END),entry8.delete(0,END),entry9.delete(0,END),entry10.delete(0,END),entry11.delete(0,END),entry12.delete(0,END),entry13.delete(0,END),entry14.delete(0,END),entry15.delete(0,END),entry16.delete(0,END),entry17.delete(0,END),entry18.delete(0,END),entry19.delete(0,END),entry20.delete(0,END),entry21.delete(0,END),menu2.set('please choose one '),menu3.set('please choose one '),menu4.set('please choose one '),menu5.set('please choose one '),menu6.set('please choose one')
    check.deselect()
    messagebox.showinfo("sucess",'data saved sucessfully')








label1=Label(window,text='Description of the Animal',font=25)
label2=Label(window,text='Kind of Animal')
entry1=Entry(window)
label3=Label(window,text='Sex')
entry2=Entry(window)
label4=Label(window,text='Age')
entry3=Entry(window)
label5=Label(window,text='color')
entry4=Entry(window)
label6=Label(window,text='Breed')
entry5=Entry(window)
label7=Label(window,text='Physically fit')
menu1=StringVar()
menu1.set('choose one')
drop1 = OptionMenu(window,menu1,*['yes','no'] )
label8=Label(window,text='ongoing treatment')
entry6=Entry(window)
label9=Label(window,text='Veterinarian name')
entry7=Entry(window)
Label(window,text='Specifics of the Caretaker/Foster',font=25).grid(row=7,column=1)
label10=Label(window,text='Caretaker/Foster’s name')
entry8=Entry(window)
label11=Label(window,text='Contact no.')
entry9=Entry(window)
label12=Label(window,text='Contact no. 2')
entry10=Entry(window)
label13=Label(window,text='Email')
entry11=Entry(window)
label14=Label(window,text='Local Residence')
entry12=Entry(window)
label15=Label(window,text='Permanent residence')
entry13=Entry(window)
Label(window,text='Specifics of the Adopter',font=25).grid(row=13,column=1)
label16=Label(window,text='Adopter\'s name')
entry14=Entry(window)
label17=Label(window,text='Contact no')
entry15=Entry(window)
label18=Label(window,text='Contact no 2')
entry16=Entry(window)
label19=Label(window,text='Line of work')
entry17=Entry(window)
label20=Label(window,text='Email')
entry18=Entry(window)
label21=Label(window,text='Local Residence')
entry19=Entry(window)
label22=Label(window,text='Permanent Residence')
entry20=Entry(window)
label23=Label(window,text='What are your plans for taking care of your pet in case you move anywhere?')
entry21=Entry(window)
label24=Label(window,text='Have you pet a dog/cat before')
menu2=StringVar()
menu2.set('choose one')
drop2 = OptionMenu(window,menu2,*['currently own','yes','no'] )
label25=Label(window,text='Your dog will primarily be an')
menu3=StringVar()
menu3.set('choose one')
drop3=OptionMenu(window,menu3,*['inside','outside'])
label26=Label(window,text='My dog/cat needs to be able to be alone (per day)')
menu4=StringVar()
menu4.set('choose one')
drop4=OptionMenu(window,menu4,*['2 hours or less','4 hours or less','4-8 hours','8-10 hours','12 hours'])
label27=Label(window,text='When you\'re not at home, your dog/cat will spend his/her time')
menu5=StringVar()
menu5.set('choose one')
drop5=OptionMenu(window,menu5,*['With the relatives','In a crate in the house','In the yard','Loose in the house','Confined to one room in the house'])
label28=Label(window,text='Do you want a guard dog')
menu6=StringVar()
menu6.set('choose one')
drop6=OptionMenu(window,menu6,*['yes','no'])

label1.grid(row=0,column=1)
label2.grid(row=1,column=0)
entry1.grid(row=1,column=1)	
label3.grid(row=2,column=0)
entry2.grid(row=2,column=1)
label4.grid(row=2,column=2)
entry3.grid(row=2,column=3)
label5.grid(row=3,column=0)
entry4.grid(row=3,column=1)
label6.grid(row=3,column=2)
entry5.grid(row=3,column=3)
label7.grid(row=4,column=0)
drop1.grid(row=4,column=1)
label8.grid(row=5,column=0)
entry6.grid(row=5,column=1)
label9.grid(row=6,column=0)
entry7.grid(row=6,column=1)
label10.grid(row=8,column=0)
entry8.grid(row=8,column=1)
label11.grid(row=9,column=0)
entry9.grid(row=9,column=1)
label12.grid(row=9,column=2)
entry10.grid(row=9,column=3)
label13.grid(row=10,column=0)
entry11.grid(row=10,column=1)
label14.grid(row=11,column=0)
entry12.grid(row=11,column=1)
label15.grid(row=12,column=0)
entry13.grid(row=12,column=1)
label16.grid(row=14,column=0)
entry14.grid(row=14,column=1)
label17.grid(row=15,column=0)
entry15.grid(row=15,column=1)
label18.grid(row=15,column=2)
entry16.grid(row=15,column=3)
label19.grid(row=16,column=0)
entry17.grid(row=16,column=1)
label20.grid(row=17,column=0)
entry18.grid(row=17,column=1)
label21.grid(row=18,column=0)
entry19.grid(row=18,column=1)
label22.grid(row=19,column=0)
entry20.grid(row=19,column=1)
label23.grid(row=20,column=1)
entry21.grid(row=21,column=1)
label24.grid(row=22,column=0)
drop2.grid(row=22,column=1)
label25.grid(row=23,column=0)
drop3.grid(row=23,column=1)
label26.grid(row=24,column=0)
drop4.grid(row=24,column=1)
label27.grid(row=24,column=0)
drop5.grid(row=24,column=1)
label28.grid(row=25,column=0)
drop6.grid(row=25,column=1)


Terms_window=Toplevel()
Terms_window.title('Terms and Conditions and Consent form')
Label(Terms_window,text='Terms and Conditions',font=('Arial',25)).pack()
Label(Terms_window,text='1) I shall not hold the organizers of the adoption camp responsible if the animal shows sign of illness or dies after adoption.',font=22).pack()
Label(Terms_window,text='2) I will not keep it tied or all by itself for long stretches of time.',font=22).pack()
Label(Terms_window,text='3) Whether I adopt a male or a female puppy/kitten, I will get it neutered/ spayed after it reaches the age of 7 months.',font=22).pack()
Label(Terms_window,text='4) In case the ownership of the dog needs to be changed, the CARETAKERS/ FOSTERS and Team Animals with Humanity will be notified and procedures will be followed.',font=22).pack()
Label(Terms_window,text=' I am aware that abandoning an adopted dog will attract penalty under Prevention of Cruelty to Animals Act.',font=22).pack()
Label(Terms_window,text='5) I will register the dog with the Municipal Corporation as per the rules.',font=22).pack()
Label(Terms_window,text='6) I have read the relevant sections of the Prevention of Cruelty Act, 1990 (Gol)* (Annex I), and am aware of the provisions of the Act.',font=22).pack()
Label(Terms_window,text='7) I agree that over the next six months, the organizers have the right to inspect the manner in which I am keeping the animal, without prior notice.',font=22).pack()
Label(Terms_window,text=' If there are any violations under the Prevention of Cruelty Act, 1960 (Gol), I am aware that the organizers may confiscate the animal or take action as per the law.',font=22).pack()
Label(Terms_window,text='').pack()
Label(Terms_window,text='In case the puppy/ kitten is found abandoned, in a bad condition or dead due to negligence of the owner,\nTeam Animals with Humanity can take a fine of Rs. 10,000/- and proceed with legal action on the adopter.',font=22).pack()
Label(Terms_window,text='In case, I (adopter) return the puppy/kitten, I (adopter) will be liable to pay a amount of Rs. 5000/-\nif returned within 1 week after adoption and Rs. 3000/- thereafter to Team Animals with Humanity.',font=22).pack()
Label(Terms_window,text='I enter into this contract of my own free will and understand that this is a binding contract enforceable by civil law.',font=22).pack()

#Terms_window.mainloop()
#Terms_window=Tk()
Label(Terms_window,text='CONSENT BY ADOPTER',font=("Arial", 25)).pack()
Label(Terms_window,text='1) I am adopting the puppy/kitten at my own risk and my responsibility. I have consulted other members of the family and they have agreed to adopt the pup/kitten.',font=22).pack()
Label(Terms_window,text='I have made sure that the puppy has been checked thoroughly by the Vet before adoption.',font=22).pack()
Label(Terms_window,text='2) I will ensure that the animal adopted by me is kept in clean, well-ventilated premises, properly fed and given regular exercise.',font=22).pack()
Label(Terms_window,text='3)In case the animal adopted by me falls ill, I will consult a vet. I will also ensure that the deworming and the vaccination schedule advised by the vet is followed.',font=22).pack()	
Label(Terms_window,text='4) I am fully aware that some diseases like gastro-enteritis, rabies, distemper, respiratory diseases, etc. cannot be diagnosed by a vet during the preliminary checkup.',font=22).pack()
Label(Terms_window,text='If the animal that I have adopted shows signs of some illness after a few days of adoption, then I will get it treated from a vet.',font=22).pack()
check=Checkbutton(Terms_window,text='I consent to the above terms',font=22)
check.pack()
Button(Terms_window,text='save and clear',command=Save).pack()
Terms_window.mainloop()
